name: Server CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vivek9352/medicare-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: sudo docker pull vivek9352/medicare-server:latest

      - name: Delete old Container
        run: sudo docker rm -f medicare-server-container || true

      - name: Re-run the Docker Container
        run: sudo docker run -d -p 3000:3000 --name medicare-server-container vivek9352/medicare-server:latest
